source 'https://rubygems.org'

gem 'jekyll', '3.8.4'
gem 'unicode'
gem 'addressable', '2.8.1'
gem 'concurrent-ruby', '1.3.4'
gem 'citeproc', '1.0.10'
gem 'rexml', '3.3.9'
gem 'ffi', '1.17.0'

group :jekyll_plugins do
  gem 'jekyll-paginate'
  gem 'jekyll-sitemap'
  gem 'jekyll-scholar'
end
